export const TEMPLATES = [
  {
    id_template: "UNDANGN1",
    name: "Undangan Pernikahan 1",
    image: "wedding_template_1.png",
    default_background_image: "wedding_1.jpg",
    primary_color: "#e3436b",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGN1",
    name: "Undangan Pernikahan 2",
    image: "wedding_template_2.png",
    default_background_image: "wedding_2.jpg",
    primary_color: "#e3436b",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGN2",
    name: "Undangan Rapat 1",
    image: "meeting_template_1.png",
    default_background_image: "meeting_1.jpg",
    primary_color: "#2f8fe5",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGN2",
    name: "Undangan Rapat 2",
    image: "meeting_template_2.png",
    default_background_image: "meeting_2.jpg",
    primary_color: "#2f8fe5",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGN3",
    name: "Undangan Keagamaan 1",
    image: "religious_template_1.png",
    default_background_image: "religious_1.jpg",
    primary_color: "#438e3e",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGN3",
    name: "Undangan Keagamaan 2",
    image: "religious_template_2.png",
    default_background_image: "religious_2.jpg",
    primary_color: "#438e3e",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGN4",
    name: "Undangan Ulang Tahun 1",
    image: "birthday_template_1.png",
    default_background_image: "birthday_1.jpg",
    primary_color: "#2f8fe5",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGN4",
    name: "Undangan Ulang Tahun 2",
    image: "birthday_template_2.png",
    default_background_image: "birthday_2.jpg",
    primary_color: "#2f8fe5",
    secondary_color: "#4a4a4a",
  },
];
