export const TEMPLATES = [
  {
    id_template: "UNDANGAN1",
    name: "Undangan Pernikahan 1",
    image: "wedding_template_1.png",
    default_background_image: "/wedding_bg/wedding_1.jpg",
    primary_color: "#e3436b",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGAN1",
    name: "Undangan Pernikahan 2",
    image: "wedding_template_2.png",
    default_background_image: "/wedding_bg/wedding_2.jpg",
    primary_color: "#e3436b",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGAN2",
    name: "Undangan Rapat 1",
    image: "meeting_template_1.png",
    default_background_image: "/meeting_bg/meeting_1.jpg",
    primary_color: "#2f8fe5",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGAN2",
    name: "Undangan Rapat 2",
    image: "meeting_template_2.png",
    default_background_image: "/meeting_bg/meeting_2.jpg",
    primary_color: "#2f8fe5",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGAN3",
    name: "Undangan Keagamaan 1",
    image: "religious_template_1.png",
    default_background_image: "/religious_bg/religious_1.jpg",
    primary_color: "#438e3e",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGAN3",
    name: "Undangan Keagamaan 2",
    image: "religious_template_2.png",
    default_background_image: "/religious_bg/religious_2.jpg",
    primary_color: "#438e3e",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGAN4",
    name: "Undangan Ulang Tahun 1",
    image: "birthday_template_1.png",
    default_background_image: "/birthday_bg/birthday_1.jpg",
    primary_color: "#2f8fe5",
    secondary_color: "#4a4a4a",
  },
  {
    id_template: "UNDANGAN4",
    name: "Undangan Ulang Tahun 2",
    image: "birthday_template_2.png",
    default_background_image: "/birthday_bg/birthday_2.jpg",
    primary_color: "#2f8fe5",
    secondary_color: "#4a4a4a",
  },
];
